#!/bin/zsh
# This hook is run after a new virtualenv is activated.

pip install --upgrade setuptools
pip install --upgrade pip
pip install ipython
pip install wheel
pip install docutils
pip install twine
pip install autopep8
